#!/usr/bin/env bash

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

redirection_rule="return 301 https://github.com/lawson;"

sudo sed -i "/server_name _;/a \\\tlocation /redirect_me {$redirection_rule}" /etc/nginx/sites-enabled/default

sudo systemctl restart nginx

