#!/usr/bin/env bash

# Update packages before installations
sudo apt-get update
sudo apt-get install -y nginx

# Create an index.html page for testing
echo "Hello World!" | sudo tee /var/www/html/index.html

# Define the redirection rule
redirection_rule="return 301 https://github.com/lawson;"

# Insert the redirection rule into the Nginx configuration
sudo sed -i "/server_name _;/a \\\tlocation /redirect_me {$redirection_rule}" /etc/nginx/sites-enabled/default

# Restart Nginx service to apply changes
sudo systemctl restart nginx

