#!/usr/bin/env bash
#Script that configure Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

redirection_rule="return 301 https://github.com/lawson;"

sudo sed -i "/server_name _;/a \\\tlocation /redirect_me {$redirection_rule}" /etc/nginx/sites-enabled/default

sudo service nginx restart

