#!/usr/bin/env bash
# Update for 404 error page

sudo apt-get update

sudo ufw allow 'Nginx HTTP'

echo 'Hello World!' |sudo tee  /var/www/html/index.html

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# code to configure redirect for a single page(/redirect_me) and add header to display hostname
string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.sciencedirect.com\/topics;"
sudo sed -i "s|server_name _;|$string_for_replacement|" /etc/nginx/sites-enabled/default

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# restart the web server after updating the settings
sudo service nginx restart
