#!/usr/bin/env bash
# This script is displaying "Best School" 9 times and Hi on the 8th time

Name="Best School"
i=1
while [[ $i -le 10 ]];
do
	echo "$Name"

	if ((i == 9));
	then
		echo "Hi"
	fi
	((i++))
done
