#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

Name="Best School"
i=1
while ((i < 20)); do
	echo $i
	case $i in
	4)
		echo "bad luck from China"
		;;
	9)
		echo "bad luck from Japan"
		;;
	17)
		echo "bad luck fro Italy"
		;;
esac
((i++))
done
