#!/usr/bin/env bash
# Displays number for each hour

((hour=0))
while ((hour <= 12)); do
	((minute=1))
	echo "Hour: $hour"
	while((minute < 60)); do
		echo "$minute"
		((minute++))
	done

	((hour++))
done
